# Generated by Django 3.0.7 on 2020-11-14 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=500)),
                ('mdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
