# Generated by Django 3.0.7 on 2020-11-15 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('apt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('pin_code', models.CharField(max_length=9)),
                ('phone', models.CharField(max_length=13)),
                ('issue', models.CharField(max_length=1000)),
                ('busno', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=15)),
                ('mdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
