# Generated by Django 3.0.7 on 2020-11-17 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20201115_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billgeneration',
            fields=[
                ('bil_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('workdone', models.CharField(max_length=1000)),
                ('futurework', models.CharField(max_length=1000)),
                ('amount', models.IntegerField(max_length=20)),
                ('user', models.CharField(max_length=15)),
                ('bdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
