# Generated by Django 3.0.7 on 2020-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_billgeneration_byuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='billgeneration',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
