# Generated by Django 3.0.7 on 2020-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_billgeneration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billgeneration',
            name='apt_id',
            field=models.IntegerField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
