# Generated by Django 3.0.7 on 2020-11-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_billgeneration_apt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billgeneration',
            name='busno',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billgeneration',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billgeneration',
            name='apt_id',
            field=models.IntegerField(),
        ),
    ]
